apiVersion: v1
kind: Secret

metadata:
  name: recon0-secret

type: Opaque

stringData:

  DB_URL: jdbc:postgresql://ep-dark-pine-ahv4wwsc-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

  DB_USERNAME: neondb_owner

  DB_PASSWORD: npg_LZGQpFh42swc

  DB_DRIVER: org.postgresql.Driver

  JWT_SECRET: NzE0YzU4NjVkNjc1NjE0ZDY5NmE0ZDYxNWYyZjZiMzU0NzY5MzczODQxM2Y2NTQzNzU0MzU3Mzg1MTNkN2E2ZA

  JWT_EXPIRATION: "86400000"

  CLOUDINARY_CLOUD_NAME: dcd1jiz7g

  CLOUDINARY_API_KEY: "653666619859712"

  CLOUDINARY_API_SECRET: Qz0kkp54zOCnJcBmYsyj-Xwdn8M

  GEMINI_API_KEY: AIzaSyD3bGAn8WMHehcwkXTGGXPW4UO4FReyt-Q

  GEMINI_API_URL: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

  REDIS_HOST: redis-service

  REDIS_PORT: "6379"