pipeline {
    agent any

    environment {
        DOCKER_USERNAME = "sujal97"
        APP_NAME="recon0-backend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Spring Boot') {
            steps {
                dir('Recon0 Backend') {
                    bat 'mvnw.cmd clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Recon0 Backend') {
                    bat 'docker build -t %DOCKER_USERNAME%/%APP_NAME%:%IMAGE_TAG% .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    dir('Recon0 Backend') {
                        bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push %DOCKER_USERNAME%/%APP_NAME%:%IMAGE_TAG%
                        docker logout
                        '''
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'ec2-key',
                        keyFileVariable: 'SSH_KEY',
                        usernameVariable: 'SSH_USER'
                    )
                ]) {
                    bat """
                    icacls "%SSH_KEY%" /inheritance:r /grant:r "%USERNAME%:R"
                    ssh -i "%SSH_KEY%" ^
                    -o StrictHostKeyChecking=no ^
                    %SSH_USER%@65.0.106.140 ^
                    "sudo kubectl set image deployment/recon0-backend recon0-backend=%DOCKER_USERNAME%/%APP_NAME%:%IMAGE_TAG% && sudo kubectl rollout status deployment/recon0-backend"
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Backend deployed successfully.'
        }
        failure {
            echo 'Backend deployment failed.'
        }
    }
}
