pipeline {
    agent any

    environment {
        DOCKER_USERNAME = "sujal97"
        APP_NAME = "recon0-frontend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Recon0 Frontend') {
                    bat 'npm install'
                }
            }
        }

        stage('Build React') {
            steps {
                dir('Recon0 Frontend') {
                    bat 'npm run build'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Recon0 Frontend') {
                    bat 'docker build -t %DOCKER_USERNAME%/%APP_NAME%:%IMAGE_TAG% .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    dir('Recon0 Frontend') {
                        bat '''
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push %DOCKER_USERNAME%/%APP_NAME%:%IMAGE_TAG%
                        docker logout
                        '''
                    }
                }
            }
        }


        stage('Deploy') {
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'ec2-key',
                        keyFileVariable: 'SSH_KEY',
                        usernameVariable: 'SSH_USER'
                    )
                ]) {
                    bat """
                    ssh -i "%SSH_KEY%" ^
                    -o StrictHostKeyChecking=no ^
                    %SSH_USER%@65.0.106.140 ^
                    "sudo kubectl set image deployment/recon0-frontend recon0-frontend=%DOCKER_USERNAME%/recon0-frontend:%IMAGE_TAG% && sudo kubectl rollout status deployment/recon0-frontend"
                    """
                }
            }
        }

    }

    post {
        success {
            echo 'Frontend image pushed successfully.'
        }

        failure {
            echo 'Frontend build failed.'
        }
    }
}